name: 'build'

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Prepare
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to GHCR
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
